name: oval-xml-feed-merge
version: '0.1.5'
base: core22
summary: A tool to merge OVAL XML feeds
description: |
    This utility is designed to merge multiple OVAL XML feeds into a single XML.
    oval-xml-feed-merge accepts a list of OVAL XML files in increasing priority.
    Any OVAL data present in the XML files in this list will replace any equivalent data in the preceding XML files.
    The tool can write the merged XML to stdout or to a file specified through the --output option.
    The --verbose flag enables logging. Logs are written to stderr.

grade: stable
confinement: strict

apps:
  oval-xml-feed-merge:
    command: bin/run-oval-xml-feed-merge.sh
    plugs:
      - home


parts:
  run-oval-xml-feed-merge:
    plugin: dump
    source: .
    organize:
      run-oval-xml-feed-merge.sh: bin/run-oval-xml-feed-merge.sh
    stage:
      - bin/run-oval-xml-feed-merge.sh

  oval-xml-feed-merge:
    plugin: python
    source: .
    source-type: git
    build-packages:
      - git
      - python3
    stage-packages:
      - libpython3.10-minimal
      - libpython3.10-stdlib
      - python3.10-minimal
      - python3.10-venv
    build-attributes:
      - enable-patchelf

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - make
      - on amd64:
        - gcc-multilib
        - g++-multilib
